# This is a config for E2B sandbox template.
# You can use 'template_id' (tpyny9n128fvpedq5scz) or 'template_name (m13v_llamaindex) from this config to spawn a sandbox:

# Python SDK
# from e2b import Sandbox
# sandbox = Sandbox(template='m13v_llamaindex')

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create({ template: 'm13v_llamaindex' })

dockerfile = "e2b.Dockerfile"
template_name = "m13v_llamaindex"
template_id = "tpyny9n128fvpedq5scz"
